//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Contexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rectangle
    {
        public int ID { get; set; }
        public int AdotX { get; set; }
        public int AdotY { get; set; }
        public int BdotX { get; set; }
        public int BdotY { get; set; }
        public int CdotX { get; set; }
        public int CdotY { get; set; }
        public int DdotX { get; set; }
        public int DdotY { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
